github.com:
    users:
        minjeuuu:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: minjeuuu
